global:
  scrape_interval: "15s"
  scrape_timeout: "10s"
  evaluation_interval: "15s"
alerting:
  alertmanagers:
    - timeout: "10s"
      api_version: v2
      path_prefix: /
      scheme: http
      follow_redirects: true
      static_configs:
        - targets:
            # - ""
rule_files:
  - "rules/*rules.yml"
scrape_configs:
  - job_name: "prometheus"
    metrics_path: /metrics
    honor_labels: false
    honor_timestamps: true
    scheme: http
    follow_redirects: true
    body_size_limit: 0
    sample_limit: 0
    label_limit: 0
    label_name_length_limit: 0
    label_value_length_limit: 0
    target_limit: 0
    static_configs:
      - targets:
          - "192.168.2.118:8081"