version: "v1"
sentinel:
  app:
    name: sentinel-gateway
    type: 0
  log:
    dir: "./logs/csp"
    usePid: false
    metric:
      maxFileCount: 14
      flushIntervalSec: 1
  stat:
    system:
      collectIntervalMs: 1000