gateway:
  proxys:
    - name: "modadmin"
      endpoints:
        - "http://192.168.2.118:8201"
      threshold: 200
    - name: "tvadmin"
      endpoints:
        - "http://192.168.2.118:99"
      threshold: 200
  restConf:
    addr: ":8081"
    timeout: 30
    maxBytes: 1048576
    middlewares:
      trace: false
      log: true
      prometheus: true
      breaker: true
      flow: true
      recover: true
      metrics: false
      gunzip: false
      blackList: true
      # sign: true
      # auth: true
      filter: true
loggers:
  "default":
    logLevel: info
    logPath: "./logs/error/error.log"
    maxSize: 128
    maxAge: 7
    maxBackups: 30
    compress: false
  "chain":
    logLevel: info
    logPath: "./logs/chain/chain.log"
    maxSize: 128
    maxAge: 7
    maxBackups: 30
    compress: false
auth:
  secret: "B63F477D-BBA3-4E52-96D3-C0034C27694A"
  prevSecret: ""
cache:
  redis:
    addr: 192.168.2.118:6379
    password: Baison789321
    db: 0
    protocol: 3
    dialTimeout: 30
    readTimeOut: 300
    writeTimeOut: 300
    poolSize: 16
    idleConns: 8
databases:
  "alimatch/modadmin":
    driver: mysql
    default: root:server123&*(@tcp(192.168.2.118:3306)/modadmin?charset=utf8&parseTime=True&loc=Local&timeout=1000ms
    idleConns: 10 
    openConns: 15
    idleTimeout: 300
    aliveTimeout: 300
    cluster: false
    sources:
      - root:server123&*(@tcp(192.168.2.118:3306)/modadmin?charset=utf8&parseTime=True&loc=Local&timeout=1000ms
    replicas:
      - root:server123&*(@tcp(192.168.2.118:3306)/modadmin?charset=utf8&parseTime=True&loc=Local&timeout=1000ms
environment: "production"
# 系统环境, 可选值: development, production
